# Cloud Run service configuration for Text Analysis API Service
# To deploy: gcloud run services replace api_service.yaml

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: text-analysis-api-service
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # CPU and memory allocation
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "2Gi"
        run.googleapis.com/cpu: "1"
        
        # Scaling configuration
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        
    spec:
      # Service account for GCP permissions
      serviceAccountName: 369455734154-compute@developer.gserviceaccount.com
      
      # Timeout for requests (5 minutes for API calls)
      timeoutSeconds: 300
      
      containers:
      - image: asia-southeast2-docker.pkg.dev/bni-prod-dma-bnimove-ai/cloud-run-source-deploy/text-analysis-api-service:latest
        
        ports:
        - containerPort: 8080
          name: http1
        
        # Environment variables
        env:
        # Google Cloud Configuration
        - name: GOOGLE_CLOUD_PROJECT
          value: "bni-prod-dma-bnimove-ai"
        - name: PUBSUB_TOPIC
          value: "character-screening-request"
        - name: FIRESTORE_DATABASE
          value: "document-processing-firestore"
        - name: PORT
          value: "8080"
        
        # Text Analysis Configuration
        - name: TEXT_ANALYSIS_ENABLED
          value: "true"
        
        # Authentication and Security Configuration
        - name: REQUIRE_AUTH
          value: "true"
        - name: AUDIT_SENSITIVE_OPERATIONS
          value: "true"
        - name: RATE_LIMIT_REQUESTS
          value: "1000"
        - name: RATE_LIMIT_WINDOW
          value: "3600"
        - name: RATE_LIMIT_BURST
          value: "100"
        
        # API Keys (in production, use Secret Manager)
        - name: API_KEYS
          value: "your-api-key-1,your-api-key-2"
        
        # Monitoring and Observability
        - name: ENABLE_METRICS
          value: "true"
        - name: LOG_LEVEL
          value: "INFO"
        
        # Resource limits
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests:
            memory: "1Gi"
            cpu: "500m"
        
        # Health checks
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
  
  traffic:
  - percent: 100
    latestRevision: true