# Cloud Run service configuration for Character Screening Worker Service
# To deploy: gcloud run services replace worker_service.yaml

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: text-analysis-worker-service
  annotations:
    run.googleapis.com/ingress: internal
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # CPU and memory allocation
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "4Gi"
        run.googleapis.com/cpu: "2"
        
        # Scaling configuration
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
        
    spec:
      # Service account for GCP permissions
      serviceAccountName: 369455734154-compute@developer.gserviceaccount.com
      
      # Timeout for requests (max 60 minutes for Cloud Run)
      timeoutSeconds: 3600
      
      containers:
      - image: asia-southeast2-docker.pkg.dev/bni-prod-dma-bnimove-ai/cloud-run-source-deploy/text-analysis-worker-service:latest
        
        ports:
        - containerPort: 8080
          name: http1
        
        # Environment variables
        env:
        # Google Cloud Configuration
        - name: GOOGLE_CLOUD_PROJECT
          value: "bni-prod-dma-bnimove-ai"
        - name: PUBSUB_SUBSCRIPTION
          value: "character-screening-worker-sub"
        - name: FIRESTORE_DATABASE
          value: "document-processing-firestore"
        - name: PORT
          value: "8080"
        
        # OpenWebUI API Configuration
        - name: OPENWEBUI_BASE_URL
          value: "https://nexus-bnimove-369455734154.asia-southeast2.run.app"
        - name: OPENWEBUI_API_KEY
          value: "sk-c2ebcb8d36aa4361a28560915d8ab6f2"
        - name: TEXT_MODEL_TIMEOUT_SECONDS
          value: "30"
        - name: TEXT_MODEL_RETRY_ATTEMPTS
          value: "3"
        
        # Custom Search API Configuration (optional)
        - name: CUSTOM_SEARCH_API_KEY
          value: ""  # Add your Google Custom Search API key if available
        - name: CUSTOM_SEARCH_ENGINE_ID
          value: ""  # Add your Custom Search Engine ID if available
        
        # Worker Configuration
        - name: MAX_CONCURRENT_JOBS
          value: "5"
        - name: JOB_TIMEOUT_SECONDS
          value: "300"
        - name: HEALTH_CHECK_INTERVAL
          value: "60"
        - name: MAX_RETRIES
          value: "3"
        - name: RETRY_DELAY_BASE
          value: "5"
        
        # Monitoring and Observability
        - name: ENABLE_METRICS
          value: "true"
        - name: LOG_LEVEL
          value: "INFO"
        
        # Resource limits
        resources:
          limits:
            memory: "4Gi"
            cpu: "2000m"
          requests:
            memory: "2Gi"
            cpu: "1000m"
        
        # Health checks
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
  
  traffic:
  - percent: 100
    latestRevision: true
